### ISSUE TITLE
Artifact in the middle

### ISSUE THREAD

**Issue by QuanhaoS** [rixez/pytorch_mri_variationalnetwork#2]
Hi Rixez,

I tried to duplicate your work and I found there is some artifacts in the middle of picture, which has the same shape as sampling mask.
I don't know how to solve it. Thanks for your help.
![18](https://user-images.githubusercontent.com/121899314/216018714-18139b9c-fc5c-4a4b-b516-c9f9afdcb2ca.png)

**Comment by rixez** [comment]
Hi QuanhaoS,
Did you try running the inference with the provided pre-trained network? If you did, did you see the same artifact?

**Comment by QuanhaoS** [comment]
I tried the pre-trained network with the error like this,

Traceback (most recent call last):
  File "run_varnet.py", line 62, in <module>
    varnet.load_state_dict(torch.load(str(save_dir/'varnet_coronal_pd_fs.h5')))
  File "/home/quanhaos/.conda/envs/pytorch_mri_vn/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1223, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for VariationalNetwork:
	size mismatch for cell_list.0.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.0.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).
	size mismatch for cell_list.1.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.1.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).
	size mismatch for cell_list.2.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.2.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).
	size mismatch for cell_list.3.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.3.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).
	size mismatch for cell_list.4.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.4.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).
	size mismatch for cell_list.5.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.5.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).
	size mismatch for cell_list.6.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.6.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).
	size mismatch for cell_list.7.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.7.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).
	size mismatch for cell_list.8.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.8.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).
	size mismatch for cell_list.9.conv_kernel: copying a param with shape torch.Size([48, 1, 11, 11, 2]) from checkpoint, the shape in current model is torch.Size([24, 1, 11, 11, 2]).
	size mismatch for cell_list.9.activation.w: copying a param with shape torch.Size([1, 48, 1, 1, 31]) from checkpoint, the shape in current model is torch.Size([1, 24, 1, 1, 31]).

**Comment by rixez** [comment]
This error is because the default number of features in the network (24) is different than the number of the trained weight (48). Please add `--features_out 48` to the command and try again.

**Comment by MahdiSaberii** [comment]
I fixed it with replacing the fftc2d() and ifftc2d() functions:

    def fftc2d(x):

    x = ifftshift(x, axis=(-3,-2))
    x = torch.fft.fftn(x,axis=(-3,-2),norm='ortho')
    x = fftshift(x,axis=[-2,-3])
    return x

    def ifftc2d(x):

    x = ifftshift(x,axis=[-3,-2])
    x = torch.fft.ifftn(x,dim=(-3,-2),norm='ortho')
    x = fftshift(x,axis=[-3,-2])
    return x

you can also use the general torch.fft.fftn and torch.fft.ifftn:
x = torch.fft.fftshift(torch.fft.fftn(torch.fft.ifftshift(x, dim=[-3,-2]),dim=[-3,-2] , norm='ortho'), dim=[-3,-2])
x = torch.fft.ifftshift(torch.fft.ifftn(torch.fft.fftshift(x , dim=[-3,-2]),dim=[-3,-2] ,norm='ortho'), dim=[-3,-2])
